# Dependencies
markdown            : redcarpet
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
gems                : ["jekyll-paginate"]

# Permalinks
permalink           : pretty

# Setup
title               : Tim's Tech Notes
tagline             : 'Life is short, we need python'
description         : 'AI, Deep Learning, Machine Learning, Computer Vision, Math'
baseurl             : /

author              : Tim Ho
name                : 'Tim Ho'
url                 : https://timctho.github.io/

paginate            : 5

# Custom vars
version             : 0.1.0
facebook_username   : timctho
github_username     : timctho

